export const SELECT_INSTALLATION= 'SELECT_INSTALLATION';
export const ADD_INSTALLATION = 'ADD_INSTALLATION';
export const CREATE_INSTALLATION = 'CREATE_INSTALLATION';
export const DELETE_INSTALLATION = 'DELETE_INSTALLATION';
export const UPDATE_INSTALLATION = 'UPDATE_INSTALLATION';
export const UPDATE_INSTALLATION_MONITOR = 'UPDATE_INSTALLATION_MONITOR';

export const SELECT_SPACE = 'SELECT_SPACE';
export const ADD_SPACE = 'ADD_SPACE';
export const CREATE_SPACE = 'CREATE_SPACE';
export const DELETE_SPACE = 'DELETE_SPACE';
export const UPDATE_SPACE = 'UPDATE_SPACE';
export const CLEAR_SPACE = 'CLEAR_SPACE';

export const SELECT_ITEM = 'SELECT_ITEM';
export const ADD_ITEM = 'ADD_ITEM';
export const CREATE_ITEM = 'CREATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
